### ISSUE TITLE
Procedure usp_sqlwatch_internal_add_index failes with constrained violation

### ISSUE THREAD

**Issue by DiHo78** [marcingminski/sqlwatch#116]
Hi there,

the above mentioned procedure failes with error
Violation of UNIQUE KEY constraint 'uq_sqlwatch_meta_index'. Cannot insert duplicate key in object 'dbo.sqlwatch_meta_index'. The duplicate key value is (MyServer, 23, IX_SnapshotDataId)

This error occurs because there a some indexes with the same name on different tables in the same database.
However, since sometimes it is a 3rd party application, I cannot change the indexes in the related databases.
Example: I got the error today from a ReportServer Database.

Maybe we can change the constraint uq_sqlwatch_meta_index to make information more unique.

Regards
Dirk

**Comment by marcingminski** [comment]
Hi, I believe this is already fixed in 2.2 beta: https://github.com/marcingminski/sqlwatch/commit/bcb92d283988acccb1860ace6a57a03a4666c18d
Are you able to apply proc from 2.2 and re-test please?

You may notice ReportServer databases are not actually captured in SQLWATCH anymore. They were never supposed to be but they were misspelt and just recently fixed: https://github.com/marcingminski/sqlwatch/pull/109.

**Comment by DiHo78** [comment]
Hi Marc,

I'll check the beta version. ReportServer database wasn't the only DB though.  
I have a few DBs, where I am not in control of the design. Unfortunately in those DBs there are also same idx names on different tables.

I'll re-test as soon as I can an let you know.

Regards
Dirk

**Comment by DiHo78** [comment]
Ha,
that is really great.
I just had a look at the fix you have mentioned. This is exactly the same fix I implemented by myself on my first test server, where I play around with SQLWatch.
In that case the issue can be closed.
