### ISSUE TITLE
Violation of UNIQUE KEY constraint 'uq_sqlwatch_meta_index' in stored procedure dbo.usp_sqlwatch_internal_add_index

### ISSUE THREAD

**Issue by MartinBarhon** [marcingminski/sqlwatch#178]
There is problem with index uq_sqlwatch_meta_index on table sqlwatch_meta_index.
When I have table without clustered index (HEAP) and index with the same name like table name I have error

Msg 2627, Level 14, State 1, Procedure dbo.usp_sqlwatch_internal_add_index, Line 76 [Batch Start Line 0]
Violation of UNIQUE KEY constraint 'uq_sqlwatch_meta_index'. Cannot insert duplicate key in object 'dbo.sqlwatch_meta_index'. The duplicate key value is ...

in procedure dbo.usp_sqlwatch_internal_add_index.

Reproduce with:
CREATE TABLE [dbo].[Test1](
	[ID] [int] NOT NULL
) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX [Test1] ON [dbo].[Test1]
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

When I drop index uq_sqlwatch_meta_index I get two rows for this table:

sql_instance	sqlwatch_database_id	sqlwatch_table_id	sqlwatch_index_id	index_name	index_id	index_type_desc	date_created	date_updated	date_last_seen	is_record_deleted
512-SQL-A01	21	19912	5940823	Test2	0	HEAP	2020-06-24 18:28:28.147	NULL	2020-06-24 18:28:28.147	NULL
512-SQL-A01	21	19912	5940824	Test2	2	NONCLUSTERED	2020-06-24 18:28:28.147	NULL	2020-06-24 18:28:28.147	NULL

SQLWATCH 2.5.7460.35921
SQL Server 2017

**Comment by marcingminski** [comment]
Hi,

the primary key is `[sql_instance],[sqlwatch_database_id], [sqlwatch_table_id], [sqlwatch_index_id]` 
and the additional constraint `[sql_instance], [sqlwatch_database_id], [sqlwatch_table_id], [index_name]` was to prevent inserting indexes with the same name but I do think this is valid since, as you say, it will clash with HEAP name. 

The only thing that will need tweaking is the dashboard its not currently expecting more than 1 row per index_name
