### ISSUE TITLE
dbo.usp_sqlwatch_trend_perf_os_performance_counters is failing on primary key violatation

### ISSUE THREAD

**Issue by mmbednarz** [marcingminski/sqlwatch#215]
Hi, 

dbo.usp_sqlwatch_trend_perf_os_performance_counters is failing with massage:

Msg 2627, Level 14, State 1, Procedure dbo.usp_sqlwatch_trend_perf_os_performance_counters, Line 64 [Batch Start Line 0]
Violation of PRIMARY KEY constraint 'pk_sqlwatch_trend_perf_os_performance_counters'. Cannot insert duplicate key in object 'dbo.sqlwatch_trend_perf_os_performance_counters'. 

Server info:
Microsoft SQL Server 2019 (RTM-CU8) (KB4577194) - 15.0.4073.23 (X64)   Sep 23 2020 16:03:08   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

SQLWATCH version: 2.5.7507.41097 (Most recent avaible to install via dbatools)

**Comment by mike-halford** [comment]
Same issue.

dbo.usp_sqlwatch_trend_perf_os_performance_counters starting to fail over the last 5 days with error

Violation of PRIMARY KEY constraint 'pk_sqlwatch_trend_perf_os_performance_counters'. Cannot insert duplicate key in object 'dbo.sqlwatch_trend_perf_os_performance_counters'.

Server Info:
Microsoft SQL Server 2017 14.0.3356.20

SQLWatch Info
Version 2.6

**Comment by dtaylor293** [comment]
I believe this is happening because of the TODATETIMEOFFSET function used in usp_sqlwatch_trend_perf_os_performance_counters.

This would have started creating duplicate entries following the clocks going back at the weekend. You could temporarily amend the stored procedure to change the select and group by as follows;

USE [SQLWATCH]
GO
/****** Object:  StoredProcedure [dbo].[usp_sqlwatch_trend_perf_os_performance_counters]    Script Date: 28/10/2020 08:52:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[usp_sqlwatch_trend_perf_os_performance_counters]
as

set xact_abort on;
set nocount on;

declare @snapshot_time datetime2(0)

/* TODO - Retention */

----15 minutes
--select @snapshot_time = max(snapshot_time)
--from [dbo].[sqlwatch_trend_perf_os_performance_counters]
--where [trend_interval_minutes] = 15
--and sql_instance = @@SERVERNAME

--insert into [dbo].[sqlwatch_trend_perf_os_performance_counters]
--select pc.[performance_counter_id]
--      ,pc.[instance_name]
--      ,[snapshot_time] = t.[interval_minutes_15]
--      ,pc.[sql_instance]
--      ,[cntr_value_calculated] = avg(pc.[cntr_value_calculated])
--	  ,[aggregation_interval_minutes] = 15
--  from [dbo].[sqlwatch_logger_perf_os_performance_counters] pc
  
--  inner join [dbo].[sqlwatch_logger_snapshot_header] h
--	on pc.sql_instance = h.sql_instance
--	and pc.snapshot_time = h.snapshot_time
--	and pc.snapshot_type_id = pc.snapshot_type_id
  
--  inner join [dbo].[vw_sqlwatch_report_dim_time] t
--	on t.[report_time] = h.[report_time]

--  inner join [dbo].[sqlwatch_meta_performance_counter] mpc
--	on mpc.performance_counter_id = pc.performance_counter_id
--	and mpc.sql_instance = pc.sql_instance

-- -- left join [dbo].[sqlwatch_aggregate_perf_os_performance_counters] apc
--	--on apc.sql_instance = pc.sql_instance
--	--and apc.performance_counter_id = pc.performance_counter_id
--	--and apc.snapshot_time = t.[interval_minutes_15]
--	--and apc.[aggregation_interval_minutes] = 15
 
-- --exclude base counters
--  where mpc.cntr_type <> 1073939712
--  and t.[interval_minutes_15] < dateadd(minute,-15,getutcdate())
--  and t.[interval_minutes_15] > isnull(@snapshot_time,'1970-01-01')
--  --and apc.snapshot_time is null

--  group by  pc.[performance_counter_id]
--      ,pc.[instance_name]
--      ,pc.[sql_instance]
--	  ,t.[interval_minutes_15]
--  option (recompile);


--60 minutes
select @snapshot_time = max([report_time])
from [dbo].[sqlwatch_trend_perf_os_performance_counters]
where [trend_interval_minutes] = 60
and sql_instance = @@SERVERNAME

insert into [dbo].[sqlwatch_trend_perf_os_performance_counters] (
	performance_counter_id
	, instance_name
	, report_time
	, sql_instance
	, cntr_value_calculated_avg
	, cntr_value_calculated_min
	, cntr_value_calculated_max
	, trend_interval_minutes
	, snapshot_time_offset
	)
select DISTINCT pc.[performance_counter_id] --performance_counter_id
      ,pc.[instance_name] --instance_name
      ,[snapshot_time] = t.[interval_minutes_60] --Report_time 
      ,pc.[sql_instance] --SQL_instance
      ,[cntr_value_calculated_avg] = avg(pc.[cntr_value_calculated])
	  ,[cntr_value_calculated_min] = min(pc.[cntr_value_calculated])
	  ,[cntr_value_calculated_max] = max(pc.[cntr_value_calculated])
	  ,[aggregation_interval_minutes] = 60 --trend_interval_minutes
	  ,[snapshot_time_offset] = t.[interval_minutes_60]
	  --,[snapshot_time_offset] = TODATETIMEOFFSET ( t.[interval_minutes_60] , h.snapshot_time_utc_offset )  
  from [dbo].[sqlwatch_logger_perf_os_performance_counters] pc
  
  inner join [dbo].[sqlwatch_logger_snapshot_header] h
	on pc.sql_instance = h.sql_instance
	and pc.snapshot_time = h.snapshot_time
	and pc.snapshot_type_id = pc.snapshot_type_id
  
  inner join [dbo].[vw_sqlwatch_report_dim_time] t
	on t.[report_time] = h.[report_time]

  inner join [dbo].[sqlwatch_meta_performance_counter] mpc
	on mpc.performance_counter_id = pc.performance_counter_id
	and mpc.sql_instance = pc.sql_instance

 -- left join [dbo].[sqlwatch_aggregate_perf_os_performance_counters] apc
	--on apc.sql_instance = pc.sql_instance
	--and apc.performance_counter_id = pc.performance_counter_id
	--and apc.snapshot_time = t.[interval_minutes_60]
	--and apc.[aggregation_interval_minutes] = 60
 
 --exclude base counters
  where mpc.cntr_type <> 1073939712
  and t.[interval_minutes_60] < dateadd(minute,-60,getutcdate())
  and t.[interval_minutes_60] > isnull(@snapshot_time,'1970-01-01')
  --and apc.snapshot_time is null

  and pc.sql_instance = @@SERVERNAME

  group by  pc.[performance_counter_id]
      ,pc.[instance_name]
      ,pc.[sql_instance]
	  ,t.[interval_minutes_60]
	  --,TODATETIMEOFFSET ( t.[interval_minutes_60] , h.snapshot_time_utc_offset )
  option (recompile);

**Comment by mike-halford** [comment]
Thanks @dtaylor293 

The recommend fix has worked.

**Comment by mmbednarz** [comment]
Yep, it works for me either.

**Comment by vkotturi** [comment]
I noticed this issue since time change Nov 1st 0200. We need to find out how this timeoffset is being handled in first place. 
Table: [sqlwatch_trend_perf_os_performance_counters]
Primary Key columns: report_time, trend_interval_minutes, sql_instance, performance_counter_id, instance_name
My observations:
1. Group BY has this time offset TODATETIMEOFFSET ( t.[interval_minutes_60] , h.snapshot_time_utc_offset )
2. We need to see how the h.snapshot_time_utc_offset in [dbo].[sqlwatch_logger_snapshot_header] is being managed here. Whether it is taking the offset change during time change or not. 
3. As the clock set back by 1 hour, if the above timeoffset calculation is resulting same value then it causing duplicate record
4. @dtaylor293 - I believe your fix causes the data to mismatch with target column which is supposed to include offset 
5. I am sure that SQLwatch team can quickly figure out the fix if they can take a quick look here.

Thanks for the great tool. 
Kotturi

**Comment by marcingminski** [comment]
The persistent timeoffset was probably a bad idea. It should just take the last `snapshot_time` for the timeslice. For example, for each hourly calculations it should take the very last snapshot in that hour i.e. 23:59:59. This would be in the UTC format from the header table and then calculate timeoffset either as computed column or in the view. 

I will see if I can fix this in 3.0 and may provide some migration scripts to retain data when upgrading from 2.x

**Comment by vkotturi** [comment]
Hi Marcin,

First of all a big thank you for this tool to the community.

I work for Rackspace as DBA and I recently tested this awesome tool. At Rackspace we recently suggested and deployed for couple of customers.

The idea from your reply looks good.  Also may be primary key can be a simple Identity column too.

Once again thank you for the nice tool. I will look for opportunity to contribute.

Thanks
Kotturi

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
