### ISSUE TITLE
Grafana Dashboard - "SQL Instance Overview>Long Queries/Wait Events" panels missing details, displays missing field(s) error

### ISSUE THREAD

**Issue by TArmstrong24** [marcingminski/sqlwatch#344]
**Did you check DOCS to make sure there is no workaround?**
Yes

**Describe the bug**
When viewing the 'SQL Instance Overview' in the Grafana dashboard, missing fields prevent the Long Queries/Wait details to display

**To Reproduce**
1. Install SQL Instance Overview > Grafana dashboard via the SQL Instance Overview.json 
2. Force long running query or wait

**Expected behavior**
Expect to see the details of any long running queries display in the panel
 
**Additional context**
There were 3 fields (sql_text, database_name and object_name) removed from vw_sqlwatch_report_fact_xes_long_queries in the 4.0 release that were utilized by these dashboards. This could be fixed in a couple different ways, either we add the query plan hash statement from sqlwatch_meta_query_plan_hash to the view (this will get us the sql text but not database name or object name) or we modify the dashboard query to join sqlwatch_logger_xes_long_queries/sqlwatch_logger_xes_wait_event and parse out the event_data (this will get us the sql text and database name). The latter also gives us the 'real' sql that caused the long query which may be crucial. I like the second method as the actual SQL text may not be needed when executing the view(s). I have made a changes using the second method and will be sending a PR. Let me know if there is another preference.

**Comment by marcingminski** [comment]
Thanks for this! I wish I could give a "bug hunter" badge! 

I think these fields should be put back into the `vw_sqlwatch_report_fact_xes_long_queries` view. I am not sure why they are gone, probably a collateral damage when I was changing/fixing the plan collection.

We should be able to get `database_id` and `procedure_id` from the `sqlwatch_meta_query_plan` now (providing we were able to collect execution plan for the query). 

If there is no plan, we could failback to parsing this data out of the raw `event_data` in `[dbo].[sqlwatch_logger_xes_long_queries]`

The reason I'd like to keep the view consistent is because that view will also feed the Power BI

**Comment by TArmstrong24** [comment]
Sounds good! I will take a shot at it and send the PR in the next couple of hours.

**Comment by marcingminski** [comment]
Thank you kindly!

**Comment by marcingminski** [comment]
May be worth to mention how I envisaged this.
Each plan in `sqlwatch_meta_query_plan` has foreign key to the `sqlwatch_meta_procedure`. I have also added a dummy procedure: `Ad-Hoc Query 3FBE6AA6` that is a placeholder for ad-hoc queries. This way we can have the following chain:

Database -> Procedure (Query) -> Plan -> Plan Hash (SQL Text)

The storage of the actual SQL Text is tricky because it could become large really fast.
I am storing Text for each Plan Hash which should minimise the number of similar queries being stored in the table.

So, to get the actual SQL text for the plan, we need to join ` [dbo].[sqlwatch_meta_query_plan_hash]` on `sql_instance` and the `query_plan_hash`

Of course, there is a chance that we haven't captured the SQL Query becuase the plan was 0x00 or was evicted from the buffer hence why I'm keeping the original event data xml
