### ISSUE TITLE
Collect Database and individual tables growth history

### ISSUE THREAD

**Issue by leedsdata** [marcingminski/sqlwatch#9]
**Is your feature request related to a problem? Please describe.**
To record database and individual tables (clustered/non-clustered indexes and heaps) size at time intervals

**Describe the solution you'd like**
Ideally: Ability to adjust frequency of when collection is taken - however regular intervals should be taken to enable the best report display
Collection of size of clustered/non-clustered indexes and heaps at time taken, stored into repository
DB size - overall DB size, or file size?

**Describe alternatives you've considered**
None.

**Additional context**
We need to be careful with this collection mechanism, as certain indexes can be very large and collection could impact performance. We should aim to test this with very large heaps/clustered/non-clustered indexes.

Wanted to raise as an official feature request, so we can open comments about implementation

**Comment by marcingminski** [comment]
good idea - did you see the roadmap, Dan - on the first page? I have this covered and partially coded already :)
in fact, should we put all of the roadmap points as feature requests so we can start the discussion?

**Comment by leedsdata** [comment]
i think so yes! It allows others to add comments about the design

**Comment by marcingminski** [comment]
I have been thinking how to best implement this using the same snapshot_header table. If I introduce a snapshot type it will be possible to have different retention periods for different collections. i.e. 7 days for every-minute performance collector and 12 months for once-per-day sizing and growth collector driven from the same header table. We can also introduce new `INT` `PK` instead of the current `DATETIME` as with more than 1 collection job there is a tiny risk that we get `PK` violation if two collectors run at the same time - although - I'd use `SYSTEMDATE()` which has higher resolution that `GETDATE()` so the chance is small, very small. I am tempted to go with the date alone for simplicity and code fail-safe check for the less frequent jobs. Thoughts?

**Comment by marcingminski** [comment]
Actually, I think composite PK will be much better approach
```sql
CREATE TABLE [dbo].[sql_perf_mon_snapshot_header]
(
	[snapshot_time] datetime,
	[snapshot_type_id] tinyint not null default 1 foreign key references dbo.[sql_perf_mon_config_snapshot_type]([snapshot_type_id]),
	 CONSTRAINT pk_snapshot PRIMARY KEY (
		[snapshot_time],[snapshot_type_id]
	)
)
```

testing it now :-)

**Comment by marcingminski** [comment]
database growth and disk utilisation completed, I am going to split the table element into a new feature as it may need a different approach. Database growth runs every hour but the same for tables may be difficult with a large number of tables.
