### ISSUE TITLE
Add explicit transactions to handle row locking

### ISSUE THREAD

**Issue by marcingminski** [marcingminski/sqlwatch#97]
Currently there are implicit transactions in the collector procedures.
This brings two problems:

# Collection failure.
When the collector fails, the snapshot header will not be rolled back. This is not the end of the world.

# Central repository feed
Central repository imports data based on the header table. It first finds any new headers not already in the central repo and imports them, then, it imports any related detail from each of the collect tables. Without explicit transactions, the header will be committed whilst long collector i.e. indexes can still be in the flight and thus, the import will be incomplete. We need explicit transaction and read committed import, possibly with `READPAST` so we do not attempt to import snapshot currently in progress.

**Comment by alexander-suprun** [comment]
Just as an option. Instead of using transactions it might be easier to create a flag in a header table and mark the record as completed at the end of the collector. If the collector fails the record will be left as uncompleted and can be potentially deleted later or left as is. Central repository will simply skip uncompleted records. Less transactions and less potential blocking.
By the way I could not find any central repositories, is it still work in progress?

**Comment by marcingminski** [comment]
Hi, yes this is work in progress. I have it working but still testing, changing and tweaking. 
I am also considering a flag which could also be used for the central repository to mark records already imported:
1. collector starts and creates snapshot record with status flag null or 0
2. collector completes and marks the status flag to 1 
3. central repository collects records marked as 1 and sets to 2 after completion.

**Comment by alexander-suprun** [comment]
Are you going to use "flag=1" in order to decide what records to extract instead of timestamp? But you still have to check if the data is already loaded into central repository to avoid duplicate errors, just in case the databases become unsynchronized for whatever reason.
I've also been working recently on collecting data from multiple servers (700+) into central repository. Not performance stats but more like inventory data. Just servers, databases, files etc. I wonder what kind of technology you decided on using to extract data from multiple servers and loading into central repository: linked servers, open query, SSIS, powershell?

**Comment by marcingminski** [comment]
introduced in 2.0
